# Generated by Django 4.0.4 on 2022-04-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
